# North American Bird Banding Program (NABBP) 2025 Lookup Tables

In [2]:
from birds.source_data.nabbp import LookupTables

In [3]:
lookup = LookupTables()

In [4]:
lookup.age.head()

,AGE_CODE,AGE_ALPHA_CODE,AGE_DESCRIPTION,AGE_EXPLAIN_TEXT
0,0,U,Unknown,A bird that cannot be placed in any classes be...
1,1,AHY,After Hatching Year,A bird known to have hatched before the calend...
2,2,HY,Hatching Year,A bird capable of sustained flight and known t...
3,3,J,Juvenile,"OBSOLETE, old code used for nestling or recent..."
4,4,L,Local,A nestling or young bird incapable of sustaine...

In [5]:
lookup.band_status.head()

  BAND_STATUS_CODE                            BAND_STATUS_DESCRIPTION
0                0                                      Original band
1                1                                   Replacement Band
2                2                                    Additional Band
3                4  Bands identified as multiple when encounter wa...
4                5                                          Band lost

In [6]:
lookup.band_type.head()

  BAND_TYPE_CODE                       BAND_TYPE_DESCRIPTION BAND_CLOSURE
0             41  aluminum\butt-end (toll-free /web address)           BE
1             42   aluminum\lock-on (toll-free /web address)           LO
2             46     aluminum\rivet (toll-free /web address)           RI
3             47     aluminum\short (toll-free /web address)           SB
4             81               stainless steel (web address)           BE

In [7]:
lookup.bird_status.head()

,BIRD_STATUS,BIRD_STATUS_DESCRIPTION,BIRD_STATUS_EXPLAIN_TEXT
0,3,Normal wild bird.,"Normal, wild bird: released in same 10-minute ..."
1,4,"Hand-reared, game-farm or hacked bird.",Hand-reared or hacked: raised in captivity fro...
2,6,Obsolete - Experimental bird.,Obsolete. Formerly used with experimental bird...
3,9,Obsolete - Dog caught bird.,Obsolete. Formerly used with dog-caught birds ...
4,2,Transported.,"Transported to a different 10-minute block, bu..."

In [8]:
lookup.coordinates_precision.head()

   COORDINATES_PRECISION_CODE   COORDINATES_PRECISION_DESC
0                          10  centroid of 10 minute block
1                           1   centroid of 1 minute block
2                           0               exact location
3                          60   centroid of 1 degree block
4                           7              county centroid

In [9]:
lookup.country_state.head()

  COUNTRY_NAME STATE_NAME ISO_COUNTRY_CODE ISO_SUBDIVISION_CODE
0       AT SEA        NaN               AA                  NaN
1  Afghanistan        NaN               AF                  NaN
2      Albania        NaN               AL                  NaN
3      Algeria        NaN               DZ                  NaN
4      Andorra        NaN               AD                  NaN

In [10]:
lookup.event_type.head()

  EVENT_TYPE EVENT_TYPE_DESC
0          B         Banding
1          E       Encounter

In [11]:
lookup.extra_info.head()

,EXTRA_INFO_CODE,EXTRA_INFO_CODE_DESCRIPTION,EXTRA_INFO_LONG_DESCRIPTION
0,18,Blood sample taken.,Blood sample taken (contact the appropriate Bi...
1,20,Fostered or cross-fostered into wild nests.,Fostered or cross-fostered into wild nests.
2,21,"Fostered or cross-fostered into wild nests, pl...","Fostered or cross-fostered into wild nests, pl..."
3,33,"Taken from an artificial nest structure (eg, n...","Taken from an artificial nest structure (e.g.,..."
4,39,"Wing, patagial, head, back, and/or nape tag(s).","Wing, patagial, head, back, and/or nape tag(s)..."

In [12]:
lookup.how_obtained.head()

,HOW_OBTAINED_CODE,HOW_OBTAINED_DESCRIPTION,HOW_OBTAINED_CODE_STATUS,HOW_OBTAINED_SEE_ALSO_TEXT
0,87,Sight record in a different 10-minute block fr...,discontinued,Code discontinued.
1,88,Found nesting in a different 10-minute block f...,discontinued,Code discontinued.
2,89,Previously banded bird trapped and released du...,discontinued,Previously banded bird trapped and released du...
3,96,Band only,discontinued,Code discontinued.
4,97,Miscellaneous. Method of recovery not covered ...,current,Miscellaneous. Method of recovery not covered ...

In [13]:
lookup.inexact_dates.head()

       INEXACT_DATE_PART INEXACT_DATE_CODE INEXACT_DATE_DESCRIPTION
0  EVENT_MONTH/EVENT_DAY             01/41    January (1st 10 Days)
1  EVENT_MONTH/EVENT_DAY             01/42    January (2nd 10 Days)
2  EVENT_MONTH/EVENT_DAY             01/43   January (Last 10 Days)
3  EVENT_MONTH/EVENT_DAY             01/99    January (Unknown Day)
4  EVENT_MONTH/EVENT_DAY             02/41   February (1st 10 Days)

In [14]:
lookup.present_condition.head()

   PRESENT_CONDITION_CODE PRESENT_CONDITION_BIRD PRESENT_CONDITION_BAND
0                       0                UNKNOWN                UNKNOWN
1                       1                UNKNOWN           LEFT ON BIRD
2                       2                UNKNOWN                REMOVED
3                       3                   DEAD                UNKNOWN
4                       4                   DEAD           LEFT ON BIRD

In [15]:
lookup.record_source.head()

  EVENT_TYPE EVENT_TYPE_DESC
0          B      Banding DB
1          E    Encounter DB
2          R    Recapture DB

In [16]:
lookup.reporting_method.head()

   REPORTING_METHOD_CODE                              REPORTING_METHOD_DESC
0                      0                                            Unknown
1                      1  The band number was reported by or as a result...
2                      2  The band number was reported by or as a result...
3                      6  Reported on the 1-800 telephone number. This c...
4                      7  Reported on the Internet. This code was added ...

In [17]:
lookup.sex.head()

   SEX_CODE               SEX_DESCRIPTION
0         0                       Unknown
1         4                          Male
2         5                        Female
3         6    Male, sexed upon recapture
4         7  Female, sexed upon recapture

In [18]:
lookup.species.head()

,SPECIES_ID,SPECIES_NAME,ALPHA_CODE,TAXONOMIC_ORDER,SCI_NAME,RECOMENDSIZE,ALLOWABLESIZE,ENDANGERED,RAPTOR,GAMEBIRD
0,0,Unidentified Dead Bird,----,NaN,NaN,N,N,NaN,NaN,NaN
1,10,Western Grebe,WEGR,100.0,Aechmophorus occidentalis,"7B, 7, 7A","7B, 7, 7A",NaN,NaN,NaN
2,11,Clark's Grebe,CLGR,102.0,Aechmophorus clarkii,"7A, 7, 7B","7A, 7, 7B",NaN,NaN,NaN
3,12,Western/Clark's Grebe,WCGR,101.0,NaN,"7A, 7B","7A, 7B",NaN,NaN,NaN
4,20,Red-necked Grebe,RNGR,98.0,Podiceps grisegena,"7A, 7, 7B","7A, 7, 7B",NaN,NaN,NaN

In [19]:
lookup.who_obtained.head()

,WHO_OBTAINED_CODE,WHO_OBTAINED_DESCRIPTION,WHO_OBTAINED_EXPLAIN_TEXT
0,20,MISCELLANEOUS,From a source not included in any other catego...
1,21,FINDER,The band was reported either by the person who...
2,22,"STATE, PROVINCIAL, OR FEDERAL","This code is used when State, Provincial, or F..."
3,23,BIRD BANDERS,This code is used to identify band numbers rep...
4,24,U. S. PARTS COLLECTION SURVEY,Each year the U. S. Fish and Wildlife Service ...